apiVersion: v1
kind: Pod
metadata:
  name: memory-request-limit-3
  namespace: memory-example
spec:
  containers:
    - name: memory-request-limit-demo-3
      image: polinux/stress
      resources:
        requests:
          memory: "1000Gi"
        limits:
          memory: "1000Gi"
      command:
        - "stress"
      args: ["--vm","1","--vm-bytes","150M","-vm-hang","1"]
        
          