apiVersion: v1
kind: Pod
metadata:
  name: memory-request-limit-1
  namespace: memory-example
spec:
  containers:
    - name: memory-request-limit-demo-1
      image: polinux/stress
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Mi"
      command:
        - "stress"
      args: ["--vm","1","--vm-bytes","150M","-vm-hang","1"]
        
          